name: github_connection

on: 
  workflow_dispatch: 
  push:
    branches:
    - main

jobs:
  build:
  runs-on: ubuntu-22.04
  steps: Checkout Repo
  uses: actions/checkout@v3

 # 3. tmate SSH 调试
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 30
      with:
        limit-access-to-actor: true   # 只允许你自己连接（安全）
