name: SSH to GitHub Actions

on: workflow_dispatch

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: 克隆仓库源码
        uses: actions/checkout@v4
      - name: Start SSH via tmate
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false  # 默认 false 就行，不限制 GitHub 账号
